# Generated by Django 3.2.6 on 2021-11-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, null=True),
        ),
    ]
