# Generated by Django 3.2.6 on 2021-10-18 09:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_home',
            name='short',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
